version: "3.9"
services:
  app:
    build: ./app
    container_name: app-container
    tty: true
    working_dir: /__work/app
    volumes:
      - ./app:/__work/app
    ports:
      - 8080:8080

  db:
    build: ./external/db
    container_name: db-container
    working_dir: /__work/db
    volumes:
      - ./external/db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
